### ISSUE TITLE
Add display styles for right-to-left languages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pandora#68]
Scribes of the Cairo Geniza will be entering text in Hebrew and Arabic, so the text input and the various display components should support RTL rendering.

**Comment by eatyourgreens** [comment]
At its simplest, this is a case of adding `lang` attributes to components, plus the following CSS:
```css
[lang=he], [lang=ar] {
  direction: rtl
}
```
